config/routes.rb
Rails.application.routes.draw do

resources :sessions, :only => [:new, :create, :destroy]
resources :users
resources :beers
resources :reviews
resources :beer_categories

resources :collections
resources :friends
resources :contacts, :only => [:new, :create]
resources :password_resets, :only => [:new, :create, :edit, :update]
resources :deals

  get 'sessions/new'
  get '/contact', :to => 'contacts#new'
  get '/admin_beers',   :to => 'pages#administration_beers'
  get '/admin_deals', :to => 'pages#administration_deals'
  get '/addbeer', :to => 'beers#new'
  get '/upload_img', :to => 'beers#upload_img'
  get '/handle_beers', :to => 'beers#index'
  get '/collections', :to => 'collections#show'
  get '/collections', :to => 'collections#destroy'
  get '/friends', :to => 'friends#show'
  get '/signup',  :to => 'users#new'

  get '/friendsRequest', :to => 'users#friendsRequest'
  get '/users',   :to => 'users#show'
  get '/handle_users', :to => 'users#index'
  post '/mlogin', :to => 'users#mlogin'

  get '/password_resets', :to => 'password_resets#new'

  get '/signin',  :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy', via: 'delete'
  get '/reviews', :to => 'reviews#show'
  root :to => 'pages#home'

  post '/api_login', :to => 'web_services#login'
  post '/api_register', :to => 'web_services#register'
  post '/api_beer_profile', :to => 'beers#show'
  get '/api_beer_profile', :to => 'beers#show'
  post '/api_add_beer', :to => 'collections#add_beer'
  post '/api_collection', :to => 'collections#show'
  post '/api_delete_beer', :to => 'collections#delete_beer'
  post '/api_user_profile', :to => 'users#api_show'
  get '/api_user_profile', :to => 'users#api_show'
  get '/api_bars', :to => 'bars#index'
  get '/api_shops', :to => 'shops#index'
  post '/api_comp', :to => 'web_services#img_comparator'
  get 'api_deals', :to => 'deals#index'
  post '/api_bars', :to => 'bars#index'
  post '/api_shops', :to => 'shops#index'
  post '/api_deals', :to => 'deals#index'

  get '/api_friends_map', :to => 'web_services#map_friends'
  post '/api_friends_map', :to => 'web_services#map_friends'
  get '/api_comp', :to => 'web_services#img_comparator'

  post '/api_add_catalogue', :to => 'web_services#add_to_catalogue'

  post '/api_friendlist', :to => 'friends#showFriendList'
  get '/api_friendlist', :to => 'friends#showFriendList'

  get '/api_beer_profile', :to => 'beers#show'

  post '/api_catalogue', :to => 'beer_categories#index'
  get '/catalogue', :to => 'beer_categories#index'
  post '/catalogue', :to => 'beer_categories#index'

  post '/addFriend', :to => 'friends#addFriend'
  get '/addFriend', :to => 'friends#addFriend'

  get '/users',   :to => 'users#show'
  post '/users',   :to => 'users#show'

  get '/beermap', :to => 'pages#beermap'

  get '/ajoutbonplan', :to =>'deals#new'
  post '/ajoutbonplan', :to=>'deals#new'

  get '/bonsplans', :to =>'deals#index'
  post '/bonsplans', :to =>'deals#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  login               :string
#  password            :string
#  salt                :string
#  email               :string
#  firstName           :string
#  lastName            :string
#  birthday            :date
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  password_reset      :string
#  password_reset_sent :datetime
#

require 'digest'

class User < ActiveRecord::Base

  has_one :collection
  has_one :friendlist

  attr_accessor :pwd

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  login_regex = /\A[a-z0-9_-]{3,15}$\z/i

	validates :login,  :presence => true,
                     :length   => { :maximum => 15 },
                     :format     => { :with => login_regex },
                     :uniqueness => { :case_sensitive => false }


	validates :email, :presence   => true,
                    :format     => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }


	validates :pwd, 	:presence     => true,
							      :confirmation => true,
							      :length       => { :within => 6..40 },
                    :on => [:create]

  validates :visibility,   :presence     => true
  

  # Fonction Callback -> Crypte le mot de passe avant enregistrement du user
  before_save :encrypt_password, if: :no_salt

  # Retour true (vrai) si le mot de passe correspond.
  def has_password?(submitted_password)
    password == encrypt(submitted_password)
  end

  # Authentification d"un user sur base du login/mot de passe soumis
  def self.authenticate(login, submitted_password)
    # On recherche le user sur base du login
    user = find_by_login(login)
    # On renvoie NIL si inexistant
    return nil  if user.nil?
    # On renvoie le résultat de la comparaison avec le mot de passe
    return user if user.has_password?(submitted_password)
  end

  # Authentification d'un user sur base de son id unique et du salt de son cookie
  def self.authenticate_with_salt(id, cookie_salt)
    # On cherche le user par son id unique
    user = find_by_id(id)
    # On vérifie que le salt enregistré dans le cookie est celui du user
    return nil  if user.nil?
    return user if user.salt == cookie_salt
  end

  def self.authenticate_by_mobile(id, encrypted_password)
    user = find_by_id(id)

    return nil if user.nil?
    return user if user.password == encrypted_password

  end

  # Méthode permettant l'envoi du mot de passe reset
  def send_password_reset
    generate_token(:password_reset)
    self.password_reset_sent = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver_now
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  # Méthode permettant l'envoi de mail de confirmation d'inscription
  def send_welcome
    UserMailer.welcome_mail(self).deliver_now
  end

  # Encryption du password et création du sel si nouvel utilisateur
  def encrypt_password
   # Si nouvel user, on crée son SALT
   self.salt = make_salt if new_record?
   self.password = encrypt(pwd)
  end

  private



    def no_salt
      return self.salt.nil?
    end

    # Renvoie un hash sur base du SALT et d'un string
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{login}")
    end

    def secure_hash(string)
      Digest::SHA512.base64digest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_filter :authenticate, :only => [:index, :edit, :update, :update_visibillity]

  before_filter :authenticateFriends, :only => [:show]

  # before_filter :correct_user, :only => [:edit, :update, :update_visibillity]
  # before_filter :admin_user,   :only => :destroy

  before_filter :authenticate, :only => [:edit, :update]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => [:destroy]

  def show
     if !params[:userId].nil?
      userid = params[:userId]
    else
      userid = params[:id]
    end
    
    @user = User.find(params[:id])
    @titre = @user.login
    @collection = Collection.find(user_id = params[:id])

    @collections = Collection.find(user_id = userid)
    @beers = Beer.all


    @reviews = @collections.reviews

    respond_to do |format|
      format.html
      format.json {
        render :json => {
          :login => @user.login,
          :email => @user.email,
          :firstName => @user.firstName,
          :lastName => @user.lastName,
          :nbBeers => @collection.reviews.count,
          :totalBeers => Beer.all.count
        }
      }
    end
  end

  def api_show
    @user = User.find(params[:id])
    @collection = Collection.find(user_id = params[:id])

    respond_to do |format|
      format.json {
        render :json => {
          :login => @user.login,
          :email => @user.email,
          :firstName => @user.firstName,
          :lastName => @user.lastName,
          :nbBeers => @collection.reviews.count,
          :totalBeers => Beer.all.count
        }
      }
    end
  end

  def index
    @title = "Tous les utilisateurs"
    @users = User.all
  end

  def new
     @user = User.new
     @title = "S'inscrire"
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User supprimé"
    redirect_to handle_users_path
  end

  # TODO
  def api_register
    @user_exists = User.exists?(:login => params[:login])
    @email_exists = User.exists?(:email => params[:password])

    render :json => {
      :checkUser => !@user_exists, :checkMail => !@email_exists
    }

    if(!@user_exists && !@email_exists)
      @user = User.new(:login => params[:login],
                       :email => params[:email],
                       :pwd => params[:password],
                       :pwd_confirmation => params[:password])
      @user.save

      @collection = Collection.new
      @collection.user = @user
      @collection.save
    end
  end

  def create
    @user = User.new(register_params)
    if @user.save
      @collection = Collection.new
      @collection.user = @user
      @collection.save
      @user.collection = @collection
      @user.save
      @friendlists = Friendlist.new
      @friendlists.user = @user
      @friendlists.save
      File.open("/etc/asterisk/users.conf", "a+"){|f| f << "\n[#{@user.id + 6000}](template)\nusername=#{@user.login}\nsecret=#{@user.id}\n" }
      sign_in @user
      flash[:success] = "Bienvenue dans Beer Collection!"
      redirect_to @user
      @user.send_welcome
    else
      @title = "Inscription"
      render 'new'
    end
  end

  def edit
    @title = "Édition profil"
  end


def update
  @user = User.find(params[:id])

  if @user.has_password?(params[:user][:old_password])

    ## Si mot de passe entré, le modifier
    if !params[:user][:pwd].blank? && !params[:user][:pwd_confirmation].blank?
      @user.update_attributes(password_params)
      @user.encrypt_password
    end

    if @user.update_attributes(user_params)
      flash[:success] = "Profil mis à jour !"
      redirect_to @user
    else
      @title = "Édition profil"
      render 'edit'
    end
    
  else
    @title = "Édition profil"
    flash[:failure] = "les mots de passe ne correspondent pas !"
    render 'edit'
  end
end

  private

    # Rend les paramètres accessibles sur la méthode

    def register_params
      params.require(:user).permit(:login, :email, :pwd, :pwd_confirmation)
    end

    def user_params
      params.require(:user).permit(:login, :email, :firstName, :lastName, :visibility)
    end

    def password_params
      params.require(:user).permit(:pwd, :pwd_confirmation)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def authenticate
      deny_access unless signed_in?
    end

    def authenticateFriends
       @user = User.find(params[:id])
       deny_access_friends unless current_user?(@user) || isFriend?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user) || current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.login,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
def options_for_status
  ['Ami', 'Public']
end

end

app/views/users/_user.html.erb
<tr>
  <% if !user.admin? %>
    <td><%= link_to user.login, user , :class => "brown-text text-brown"%></td>
    <td><%= user.email %></td>
    <td><%= link_to "Consulter profil",  user_path(user), :class => "brown-text text-brown" %></td>
    <td><%= button_to "Supprimer", user, :method => :delete, :onclick => "return confirm('Etes-vous sûr de vouloir supprimer #{user.login} ?')", :class => "orange lighten-2"%></td>
  <% end %>
</tr>
         

app/views/users/edit.html.erb
<div id="login-page" class="container row-login">

    <div class="col s12 row-login">
      <h3><span class="span_h3 brown-text"><%=@title%></span></h3>
      <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
      <form class="login-form">
       <div class="row">

         <div class="input-field col s12 center">

         </div>
       </div>
         <div class="row margin">
         <div class="input-field col s12">

            <i class="mdi-social-person-outline prefix"></i>
            <%= f.label :login %><br />
            <%= f.text_field :login %>
          </div>
          </div>
         <div class="row margin">
         <div class="input-field col s12">

           <i class="mdi-social-person-outline prefix"></i>
            <%= f.label :email, "eMail" %><br />
            <%= f.text_field :email %>
          </div>
      </div>

 </div>
      <div class="row margin">
      <div class="input-field col s12">

         <i class="mdi-social-person-outline prefix"></i>
         <%= f.label :lastName, "Nom" %><br />
         <%= f.text_field :lastName %>
       </div>
       </div>
       <div class="row margin">
       <div class="input-field col s12">

          <i class="mdi-social-person-outline prefix"></i>
          <%= f.label :firstName, "Prénom" %><br />
          <%= f.text_field :firstName %>
        </div>
        </div>
         <div class="row margin">
        <div class="input-field col s12">

           <i class="mdi-action-lock-outline prefix"></i>
           <%= f.label :pwd, "Nouveau mot de passe" %><br />
           <%= f.password_field :pwd %>

         </div>
        </div>
        <div class="row margin">
        <div class="input-field col s12">

           <i class="mdi-action-lock-outline prefix"></i>
           <%= f.label :pwd_confirmation, "Confirmation nouveau mot de passe" %><br />
           <%= f.password_field :pwd_confirmation %>

         </div>
        </div>


  <div class="row margin">
         <div class="input-field col s12">
<span> Visibilitée du profil : </span>
<%= f.select :visibility, options_for_status, {}, prompt: 'Select One' , :class => 'browser-default' %>

  </div>

        <div class="row margin">
         <div class="input-field col s12">

            <i class="mdi-action-lock-outline prefix"></i>
            <%= f.label :old_password, "Ancien mot de passe pour confirmation" %><br/><br />
            <%= f.password_field :old_password %>
         </div>
       </div>
        <div class="row">
           <div class="col s12 m5 l4"><p></p></div>
           <%= f.submit "Editer" , :class => "btn col s6 m3 l4 waves-light orange"%>
           <div class="col s12 m5 l4"><p></p></div>

         </div>
      </div>
    </form>
       <% end %>
    </div>
  </div>
<script src="min/plugin-min.js"></script>
<script src="min/custom-min.js"></script>

<!--  -->

app/views/users/index.html.erb
<% if signed_in? && current_user.admin? %>
<div class="container">
<h3><span class="span_h3 brown-text"><%=@title%></span></h3>
<div class="row">
  <table>
    <thead>
      <tr>
          <th data-field="name">Login</th>
          <th data-field="degree">Email</th>
      </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
          <tr>
            <% if !user.admin? %>
              <td><%= link_to user.login, user , :class => "brown-text text-brown"%></td>
              <td><%= user.email %></td>
              <td><%= link_to "Consulter profil",  user_path(user), :class => "brown-text text-brown" %></td>
              <td><%= button_to "Supprimer", user, :method => :delete, :onclick => "return confirm('Etes-vous sûr de vouloir supprimer #{user.login} ?')", :class => "orange lighten-2"%></td>
            <% end %>
          </tr>
          </tr>
        <% end %>
    </tbody>
  </table>
</div>
<% else %>
<p>Vous n'avez pas les droits pour consulter cette page !</p>
<% end %>

app/views/users/new.html.erb
<div id="login-page" class="container row-login">
  <div class="col s12 ">
    <h3><span class="span_h3 brown-text"><%=@title%></span></h3>
    <%= form_for(@user) do |f| %>
    <form class="login-form">
      <div class="row">
        <div class="input-field col s12 center">
        </div>
      </div>
       <div class="row margin">
        <div class="input-field col s12">
          <i class="mdi-social-person-outline prefix"></i>
            <%= f.label :login %><br />
            <%= f.text_field :login %>
        </div>
      </div>
       <div class="row margin">
        <div class="input-field col s12">
          <i class="mdi-social-person-outline prefix"></i>
          <%= f.email_field :email, :class => "validate" %>
          <%= f.label :email, "Email", :'data-error' => "Invalide", :'data-success' => "Valide" %><br />
        </div>
      </div>
        <div class="row margin">
        <div class="input-field col s12">
          <i class="mdi-action-lock-outline prefix"></i>
          <%= f.label :pwd, "Mot de passe" %><br />
          <%= f.password_field :pwd %>
        </div>
      </div>
      <div class="row margin">
        <div class="input-field col s12">
          <i class="mdi-action-lock-outline prefix"></i>
      <%= f.label :pwd_confirmation, "Confirmation" %><br/><br />
      <%= f.password_field :pwd_confirmation %>
        </div>
      </div>
      <%= @user.errors.full_messages.first if @user.errors.any? %>
      <div class="row">
        <div class="col s12 m5 l4"><p></p></div>
           <%= f.submit "Inscription" , :class => "btn col s6 m3 l4 waves-light orange"  %>
        <div class="col s12 m5 l4"><p></p></div>
      </div>

    </form>
      <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="card-panel grey lighten-5 z-depth-1">
    <div class="row">
      <% if signed_in? && @user.id == current_user.id %>
      <h3><span class="span_h3 brown-text">Profil</span></h3>
      <% else %>
      <h3><span class="span_h3 brown-text"><%=@title%></span></h3>
      <% end %>
      <div class="col s12 m6 l0">
        <p>
          <%= gravatar_for @user, :size => '60%', :class => 'responsive-img z-depth-2 materialboxed' %>
        </p>
      </div>
      <div class="col s12 m6 l0">
        <ul>
          <li> <b>Nom d'utilisateur :</b> <%= @user.login%></li>
          <li> <b>Email :</b> <%= @user.email %></li>
          <li> <b>Nom :</b> <%= @user.firstName %></li>
          <li> <b>Prenom :</b> <%= @user.lastName %></li>
          <% if @collection.user_id == current_user.id %>
            <li> <b>Votre collection est composée de : </b>
              <%= "#{@collection.reviews.count}  / #{@beers.count} bières !"%>
            </li>
          <% else %>
            <li> 
              <b><%= "La collection de #{User.find(id = @collection.user_id).login}  est composée de : "%></b>
              <%= "#{@collection.reviews.count}  / #{@beers.count} bières !" %>
            </li>
          <% end %>
          
          

        </ul>
     </div>
      <div class="col s12 m6 l0">
        <% if signed_in? && @user.id == current_user.id %>
          <%= link_to "Editer le profil", edit_user_path(@user), :class => "btn waves-effect waves-light orange" %>
        <% end %>
     </div>

      <div class="col s12 m6 l0">
        <br>
        <% if signed_in? && @user.id == current_user.id %>
          <%= link_to "Voir ses amis", friend_path(@user), :class => "btn waves-effect waves-light orange" %>
        <% end %>
     </div>
     


      <% $i = 0 %>
      <!-- Pour tout les users de la db -->
      <% @users = User.all %>
      <% @users.each do |user| %>
        <% if !current_user?(user) %>
            
            <% @friendlistsAmi = Friendlist.find(user_id = user.id) %>
            <% @friendsAmi = Friend.where("friendlist_id = ?", @friendlistsAmi.id) %>
            <% @friend_statuses_one = FriendStatus.find_by(users_id: current_user.id, friends_id: user.id) %>
            <% @friend_statuses_two = FriendStatus.find_by(users_id: user.id, friends_id: current_user.id) %>
            <% if @friendsAmi.exists?( :user_id =>current_user.id) %>
              <% $i = $i+1 %>
            <% end %>
            <% if !@friend_statuses_one.nil? %>
              <% if @friend_statuses_one.status == "ami" %>
                <% $i = $i-1 %>
              <% end %>
            <% end %>
            <% if !@friend_statuses_two.nil? %>
              <% if @friend_statuses_two.status == "ami" %>
                <% $i = $i-1 %>
              <% end %>
            <% end %>

        <% end %>
      <% end %>
      <div class="col s12 m6 l0">
        <br>
        <% if signed_in? && @user.id == current_user.id %>
          <%= link_to "Chercher des amis", addFriend_path,  :class => "btn waves-effect waves-light orange" %>
          <% if $i != 0 %>
            <div class="chip">
            <%= $i %> ami vous a ajouté
            </div>
          <% end %>
        <% end %>
     </div>
   </div>
  </div>
</div>
<script src="../min/plugin-min.js"></script>
<script src="../min/custom-min.js"></script>