config/routes.rb
Rails.application.routes.draw do

resources :sessions, :only => [:new, :create, :destroy]
resources :users
resources :beers
resources :reviews
resources :beer_categories

resources :collections
resources :friends
resources :contacts, :only => [:new, :create]
resources :password_resets, :only => [:new, :create, :edit, :update]
resources :deals

  get 'sessions/new'
  get '/contact', :to => 'contacts#new'
  get '/admin_beers',   :to => 'pages#administration_beers'
  get '/admin_deals', :to => 'pages#administration_deals'
  get '/addbeer', :to => 'beers#new'
  get '/upload_img', :to => 'beers#upload_img'
  get '/handle_beers', :to => 'beers#index'
  get '/collections', :to => 'collections#show'
  get '/collections', :to => 'collections#destroy'
  get '/friends', :to => 'friends#show'
  get '/signup',  :to => 'users#new'

  get '/friendsRequest', :to => 'users#friendsRequest'
  get '/users',   :to => 'users#show'
  get '/handle_users', :to => 'users#index'
  post '/mlogin', :to => 'users#mlogin'

  get '/password_resets', :to => 'password_resets#new'

  get '/signin',  :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy', via: 'delete'
  get '/reviews', :to => 'reviews#show'
  root :to => 'pages#home'

  post '/api_login', :to => 'web_services#login'
  post '/api_register', :to => 'web_services#register'
  post '/api_beer_profile', :to => 'beers#show'
  get '/api_beer_profile', :to => 'beers#show'
  post '/api_add_beer', :to => 'collections#add_beer'
  post '/api_collection', :to => 'collections#show'
  post '/api_delete_beer', :to => 'collections#delete_beer'
  post '/api_user_profile', :to => 'users#api_show'
  get '/api_user_profile', :to => 'users#api_show'
  get '/api_bars', :to => 'bars#index'
  get '/api_shops', :to => 'shops#index'
  post '/api_comp', :to => 'web_services#img_comparator'
  get 'api_deals', :to => 'deals#index'
  post '/api_bars', :to => 'bars#index'
  post '/api_shops', :to => 'shops#index'
  post '/api_deals', :to => 'deals#index'

  get '/api_friends_map', :to => 'web_services#map_friends'
  post '/api_friends_map', :to => 'web_services#map_friends'
  get '/api_comp', :to => 'web_services#img_comparator'

  post '/api_add_catalogue', :to => 'web_services#add_to_catalogue'

  post '/api_friendlist', :to => 'friends#showFriendList'
  get '/api_friendlist', :to => 'friends#showFriendList'

  get '/api_beer_profile', :to => 'beers#show'

  post '/api_catalogue', :to => 'beer_categories#index'
  get '/catalogue', :to => 'beer_categories#index'
  post '/catalogue', :to => 'beer_categories#index'

  post '/addFriend', :to => 'friends#addFriend'
  get '/addFriend', :to => 'friends#addFriend'

  get '/users',   :to => 'users#show'
  post '/users',   :to => 'users#show'

  get '/beermap', :to => 'pages#beermap'

  get '/ajoutbonplan', :to =>'deals#new'
  post '/ajoutbonplan', :to=>'deals#new'

  get '/bonsplans', :to =>'deals#index'
  post '/bonsplans', :to =>'deals#index'

end

app/models/deal.rb
# == Schema Information
#
# Table name: deals
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  start_date  :string
#  end_date    :string
#  reference   :float
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Deal < ActiveRecord::Base

  belongs_to :beer_place, :polymorphic => true
  has_one :beer


  validates :name, presence: true,
                   length: { maximum: 40},
                   uniqueness: { case_sensitive: false }


  validates :description, presence: true,
                          length: { maximum: 500}


  validates :reference, presence: true,
  				   numericality: true

  validates :start_date, presence: true


  validates :end_date, presence: true


end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    @deals = Deal.all
	  @title = "Bons plans"

    respond_to do |format|
      format.html
      format.json {
        render :json => {
          :deals => @deals
        }
      }
    end
  end

  def new
	@deal = Deal.new
	@title = "Nouveau bon plan"
  end

  def create
    @deal = Deal.new(deal_params)
    if @deal.save

      uploaded_io = params[:deal][:picture]
      File.open(Rails.root.join('public', 'images', 'deal_img', "#{ @deal.id }.jpg"), 'wb') do |file|
        file.write(uploaded_io.read)
      end

      flash[:success] = "Bon plan ajouté"
      redirect_to bonsplans_path
    else
      @titre = "Nouveau bon plan"
      render 'new'
    end
  end

  def destroy
    Deal.find(params[:id]).destroy
    flash[:success] = "Bon plan supprimé"
    redirect_to bonsplans_path
  end

  def edit
    @deal = Deal.find(params[:id])
    @title = "Editer le bon plan"
  end

  def update 
    @deal = Deal.find(params[:id])
    if @deal.update_attributes(deal_params)
      
      uploaded_io = params[:deal][:picture]
      File.open(Rails.root.join('public', 'images', 'deal_img', "#{ @deal.id }.jpg"), 'wb') do |file|
        file.write(uploaded_io.read)
      end

      flash[:success] = "Le bon plan a bien été mis à jour !"
      redirect_to bonsplans_path
    else
      @title = "Editer le bon plan"
      render 'edit' 
    end
  end 

  private

    # Rend les paramètres accessibles sur la méthode

    def deal_params
      params.require(:deal).permit(:name, :description, :reference, :start_date, :end_date, :beer_place_type, :beer_place_id, :beer_id)
    end

end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/edit.html.erb
<% if signed_in? && current_user.admin? %>
<div class="container">
  <div class="col s12 ">
    <h3><span class="span_h3 brown-text"><%=@title%></span></h3>
  <%= form_for(@deal) do |f| %>
  <form class="col s12">
    <div class="row">
       <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i>
           <%= f.label :name, "Nom du bon plan" %><br />
           <%= f.text_field :name %>
          </div>
    </div>
    <div class="row">
       <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i>
           <%= f.label :description %><br />
           <%= f.text_field :description %>
          </div>
    </div>
    <div class="row">
       <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i>   
           <%= f.label :reference %><br />
           <%= f.text_field :reference %>
          </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i> 
           <%= f.label :start_date, "Date de début" %><br />
           <%= f.datetime_local_field :start_date %>
        </div>
      </div>
     
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i> 
           <%= f.label :end_date, "Date de fin" %><br />
           <%= f.datetime_local_field :end_date %>
        </div>
      </div>

      <div class="row">
       <div class="input-field col s12">
         <%= f.label :beer_place_type, "Shop ou bar?" %><br><br>
         <%= f.select :beer_place_type, [['Shop', "Shop"], ['Bar', "Bar"]], {}, prompt: 'Choisir de valider' , :class => 'browser-default'%>
      </div>
    </div>   
      <div class="row">
       <div class="input-field col s12">
         <%= f.label :beer_place_id, "Nom du shop" %><br><br>
         <%= f.select :beer_place_id, Shop.all.collect { |cat| [cat.name, cat.id]}, {}, prompt: 'Choisir une catégorie' , :class => 'browser-default'%>
      </div>
    </div>   

      <div class="row">
         <div class="input-field col s12">
           <%= f.label :beer_id, "Nom de la bière en rapport au bon plan" %><br><br>
           <%= f.select :beer_id, Beer.all.collect { |cat| [cat.name, cat.id]}, {}, prompt: 'Choisir une catégorie' , :class => 'browser-default'%>
         </div>
      </div> 

      <div class="row">
         <div class="input-field col s12">
           <%= f.label :picture, "Image décrivant le bon plan" %><br><br>  
           <%= f.file_field :picture %>
         </div>
      </div>  

      <%= @deal.errors.full_messages.first if @deal.errors.any? %>
     <div class="row">
       <div class="col s12 m5 l4"><p></p></div>
           <%= f.submit "Editer ce bon plan" , :class => "btn col s6 m3 l4 waves-light orange"  %>
        <div class="col s12 m5 l4"><p></p></div>
      </div>
      </form>
       <% end %>
  </div>
</div>
<% else %>
  <p> Vous n'avez pas les droits requis pour accéder à cette page !</p>
<% end %>

app/views/deals/index.html.erb
<% if signed_in? %>
<div class="container">
	<h3><span class="span_h3 brown-text"><%=@title%></span></h3>
	<div class="row">
	<% # Résultat de la recherche #index %>
	<% @deals = Deal.all %>
    <% if @deals.blank? %>
      <%= "Aucun bon plan n'est disponnible!" %>
    <% else %>
		<% @deals.each do |deal| %>
		<% @beer = Beer.find_by_id(deal.beer_id) %>
				<div class="col s12 m4">
						<div class="card">
							<div class="card-image waves-effect waves-block waves-light">
							<img class="activator" src="images/deal_img/<%= deal.id %>.jpg">
						</div>
						<div class="card-content">
			<span class="card-title activator grey-text text-darken-4"><%= deal.name %><i class="material-icons right">more_vert</i></span></br>
							<p><%= deal.beer_place.name %></br>
							   <%= deal.beer_place_type %></p>
						</div>
						<div class="card-reveal">
							<span class="card-title grey-text text-darken-4"><%= deal.name %><i class="material-icons right">close</i></span>
							<p><%= deal.description %></p>
							<p>Référence : <%= deal.reference %> </br>
							<p>Date de debut : <%= deal.start_date.to_formatted_s(:long)  %></br> Date de fin : <%= deal.end_date.to_formatted_s(:long)  %>
							</p>
							<div class="card-action">
								<%= link_to @beer.name, @beer %>
							</div>
							<% if current_user.admin? %>
								<div class="card-action">
									<%= link_to "Editer ce bon plan",  edit_deal_path(deal) %><br><br> 
									<%= button_to "Retirer le bon plan", deal, :method => :delete, :onclick => "return confirm('Etes-vous sûr de vouloir supprimer le bon plan #{deal.name} ?')", :class => "orange lighten-2"%>
								</div>
								
							<% end %>
						</div>
					</div>
				</div>
		<% end %>
	<% end %>
	</div>
</div>
<% else %>
	<p> Vous n'avez pas les droits pour accéder à cette page. Veuillez créer un compte !</p>
<% end %>

app/views/deals/new.html.erb
<% if signed_in? && current_user.admin? %>
<div class="container">
  <div class="col s12 ">
    <h3><span class="span_h3 brown-text"><%=@title%></span></h3>
  <%= form_for(@deal) do |f| %>
  <form class="col s12">
    <div class="row">
       <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i>
           <%= f.label :name, "Nom du bon plan" %><br />
           <%= f.text_field :name %>
          </div>
    </div>
    <div class="row">
       <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i>
           <%= f.label :description %><br />
           <%= f.text_field :description %>
          </div>
    </div>
    <div class="row">
       <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i>   
           <%= f.label :reference %><br />
           <%= f.text_field :reference %>
          </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i> 
           <%= f.label :start_date, "Date de début" %><br />
           <%= f.datetime_local_field :start_date %>
        </div>
      </div>
     
      <div class="row">
        <div class="input-field col s12">
          <i class="material-icons prefix">mode_edit</i> 
           <%= f.label :end_date, "Date de fin" %><br />
           <%= f.datetime_local_field :end_date %>
        </div>
      </div>

      <div class="row">
       <div class="input-field col s12">
         <%= f.label :beer_place_type, "Shop ou bar?" %><br><br>
         <%= f.select :beer_place_type, [['Shop', "Shop"], ['Bar', "Bar"]], {}, prompt: 'Choisir de valider' , :class => 'browser-default'%>
      </div>
    </div>   
      <div class="row">
       <div class="input-field col s12">
         <%= f.label :beer_place_id, "Nom du shop" %><br><br>
         <%= f.select :beer_place_id, Shop.all.collect { |cat| [cat.name, cat.id]}, {}, prompt: 'Choisir une catégorie' , :class => 'browser-default'%>
      </div>
    </div>   

      <div class="row">
         <div class="input-field col s12">
           <%= f.label :beer_id, "Nom de la bière en rapport au bon plan" %><br><br>
           <%= f.select :beer_id, Beer.all.collect { |cat| [cat.name, cat.id]}, {}, prompt: 'Choisir une catégorie' , :class => 'browser-default'%>
         </div>
      </div> 

      <div class="row">
         <div class="input-field col s12">
           <%= f.label :picture, "Image décrivant le bon plan" %><br><br>  
           <%= f.file_field :picture %>
         </div>
      </div>  

      <%= @deal.errors.full_messages.first if @deal.errors.any? %>
     <div class="row">
       <div class="col s12 m5 l4"><p></p></div>
           <%= f.submit "Ajout du bon plan" , :class => "btn col s6 m3 l4 waves-light orange"  %>
        <div class="col s12 m5 l4"><p></p></div>
      </div>
      </form>
       <% end %>
  </div>
</div>
<% else %>
  <p> Vous n'avez pas les droits requis pour accéder à cette page !</p>
<% end %>