config/routes.rb
Rails.application.routes.draw do

resources :sessions, :only => [:new, :create, :destroy]
resources :users
resources :beers
resources :reviews
resources :beer_categories

resources :collections
resources :friends
resources :contacts, :only => [:new, :create]
resources :password_resets, :only => [:new, :create, :edit, :update]
resources :deals

  get 'sessions/new'
  get '/contact', :to => 'contacts#new'
  get '/admin_beers',   :to => 'pages#administration_beers'
  get '/admin_deals', :to => 'pages#administration_deals'
  get '/addbeer', :to => 'beers#new'
  get '/upload_img', :to => 'beers#upload_img'
  get '/handle_beers', :to => 'beers#index'
  get '/collections', :to => 'collections#show'
  get '/collections', :to => 'collections#destroy'
  get '/friends', :to => 'friends#show'
  get '/signup',  :to => 'users#new'

  get '/friendsRequest', :to => 'users#friendsRequest'
  get '/users',   :to => 'users#show'
  get '/handle_users', :to => 'users#index'
  post '/mlogin', :to => 'users#mlogin'

  get '/password_resets', :to => 'password_resets#new'

  get '/signin',  :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy', via: 'delete'
  get '/reviews', :to => 'reviews#show'
  root :to => 'pages#home'

  post '/api_login', :to => 'web_services#login'
  post '/api_register', :to => 'web_services#register'
  post '/api_beer_profile', :to => 'beers#show'
  get '/api_beer_profile', :to => 'beers#show'
  post '/api_add_beer', :to => 'collections#add_beer'
  post '/api_collection', :to => 'collections#show'
  post '/api_delete_beer', :to => 'collections#delete_beer'
  post '/api_user_profile', :to => 'users#api_show'
  get '/api_user_profile', :to => 'users#api_show'
  get '/api_bars', :to => 'bars#index'
  get '/api_shops', :to => 'shops#index'
  post '/api_comp', :to => 'web_services#img_comparator'
  get 'api_deals', :to => 'deals#index'
  post '/api_bars', :to => 'bars#index'
  post '/api_shops', :to => 'shops#index'
  post '/api_deals', :to => 'deals#index'

  get '/api_friends_map', :to => 'web_services#map_friends'
  post '/api_friends_map', :to => 'web_services#map_friends'
  get '/api_comp', :to => 'web_services#img_comparator'

  post '/api_add_catalogue', :to => 'web_services#add_to_catalogue'

  post '/api_friendlist', :to => 'friends#showFriendList'
  get '/api_friendlist', :to => 'friends#showFriendList'

  get '/api_beer_profile', :to => 'beers#show'

  post '/api_catalogue', :to => 'beer_categories#index'
  get '/catalogue', :to => 'beer_categories#index'
  post '/catalogue', :to => 'beer_categories#index'

  post '/addFriend', :to => 'friends#addFriend'
  get '/addFriend', :to => 'friends#addFriend'

  get '/users',   :to => 'users#show'
  post '/users',   :to => 'users#show'

  get '/beermap', :to => 'pages#beermap'

  get '/ajoutbonplan', :to =>'deals#new'
  post '/ajoutbonplan', :to=>'deals#new'

  get '/bonsplans', :to =>'deals#index'
  post '/bonsplans', :to =>'deals#index'

end

app/models/beer.rb
# == Schema Information
#
# Table name: beers
#
#  id               :integer          not null, primary key
#  name             :string
#  degree           :float
#  description      :text
#  story            :text
#  confirmed        :boolean          default(FALSE)
#  beer_category_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Beer < ActiveRecord::Base

  belongs_to :beer_category
  has_many :reviews

  #===================#
  #=== Validations ===#
  #===================#

  validates :name, presence: true,
                   length: { maximum: 40 },
                   uniqueness: { case_sensitive: false }

  validates :degree, presence: true,
                     numericality: true,
                     inclusion: { in: 0.0..100 }

  # TODO : Compléter validations sur autres champs
  validates :description, length: { maximum: 2000 }

  validates :story, length: { maximum: 2000 }



  ## Recherche des bières sur base du nom
  # => XXX La méthode devra peut-être être renomée si complexification
  #
  def self.search(name)
    if name
      self.where('name LIKE ?', "%#{name}%")
    else
      self.all
    end
  end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_filter :admin_user,   :only => [:index, :new, :update, :destroy]
  ##
  # Renvoie une entité Beer sur base d'un id
  # @param id :integer
  #

  def show
    @reviews = Review.all
    @nbReviews= Review.where("beer_id = ?", params[:id])

    @beer = Beer.find(params[:id])
    @beer_category = BeerCategory.find_by_id(@beer.beer_category.id)
    @collection = Collection.find_by_user_id(params[:userId])
    @review = Review.where("beer_id = ?", @beer.id)

    respond_to do |format|
      format.html
      format.json {
        render :json => {
          :beer => @beer.as_json.merge(:global_note => @nbReviews.average(:note)),
          :category => @beer_category,
          :review => @review
        }
      }
    end
  end

  def index
    @title = "Toutes les bières"
    @beers = Beer.order(confirmed: :asc)
  end

  def new
    @beer = Beer.new
    @title = "Ajouter une bière"
    @beer_categories = BeerCategory.all
  end

  def destroy
    Beer.find(params[:id]).destroy
    flash[:success] = "Bière supprimée avec succès"
    redirect_to handle_beers_path
  end

  def create
    @beer = Beer.new(beer_params)

    ## Ajout de la bière par l'admin
    if signed_in? && current_user.admin?
      @beer.confirmed = true
    end

    if @beer.save

      uploaded_io = params[:beer][:picture]
      File.open(Rails.root.join('public', 'images', 'beer_profile', "#{ @beer.id }.jpg"), 'wb') do |file|
        file.write(uploaded_io.read)
      end

      flash[:success] = "La bière a bien été ajoutée !"
      redirect_to @beer
    else
      @title = "Ajouter une bière"
      render 'new'
    end
  end

  def edit
    @beer = Beer.find(params[:id])
    @title = @beer.name
  end

  def update
    ### Upload de l'image de la bière depuis son profil
    if !params[:beer][:picture].blank?
      upload_img
    end

    @beer = Beer.find(params[:id])
    if @beer.update_attributes(beer_params)
      flash[:success] = "Profil de la bière actualisé."
      redirect_to handle_beers_path
    end
  end

  def upload_img
    uploaded_io = params[:beer][:picture]
    File.open(Rails.root.join('public', 'images', 'beer_profile', "#{ params[:beer][:id]}.jpg"), 'wb') do |file|
      file.write(uploaded_io.read)
    end
  end

  private

  def beer_params
    params.require(:beer).permit(:name, :degree, :description, :story, :beer_category_id, :confirmed)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/beers_helper.rb
module BeersHelper

  def nbReviews(nb)
    if nb > 1 then return true
    else return false
    end
  end

  def nbReviewsII(nb)
  	if nb > 0 then return true
    else return false
    end
  end

end

app/views/beers/_beer.html.erb
<tr>
    <% if signed_in? && @collection_beers.include?(beer.id) %>
        <td><i class="material-icons">done</i></td>
    <% else %>
        <td></td>
    <% end %>
    <td><%= link_to beer.name, beer %></td>
    <td><%= beer.degree %></td>
    <td><%= link_to beer.beer_category.name, beer.beer_category %></td>
</tr>

app/views/beers/edit.html.erb
<% if signed_in? && current_user.admin? %>
<div id="login-page" class="container row-login">

    <div class="col s12 row-login">
      <h3><span class="span_h3 brown-text"><%=@title%></span></h3>
      <%= form_for(@beer) do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>
      <form class="login-form">
       <div class="row">
         <div class="input-field col s12 center">
         </div>
       </div>

       <div class="row margin">
        <div class="input-field col s12">
            <%= f.label :name, "Nom" %><br />
            <%= f.text_field :name %>
        </div>
      </div>
       <div class="row margin">
        <div class="input-field col s12">
          <%= f.label :degree, "Degré d'alcool" %><br />
          <%= f.number_field :degree , :step => 0.1, :value => 5 %>
        </div>
       </div>
       <div class="row margin">
        <div class="input-field col s12 ">
          <%= f.label :description, "Description" %><br />
          <%= f.text_area :description , :class => "materialize-textarea" %>
        </div>
       </div>
       <div class="row margin">
        <div class="input-field col s12">
          <%= f.label :story, "Histoire" %><br />
          <%= f.text_area :story , :class => "materialize-textarea"  %>
        </div>
       </div>

       <div class="row margin">
        <div class="input-field col s12">
          <%= f.label :beer_category_id, "Catégorie" %><br><br>
          <%= f.select :beer_category_id, BeerCategory.all.collect { |cat| [cat.name, cat.id]}, {}, prompt: 'Choisir une catégorie' , :class => 'browser-default'%>
        </div>
       </div>

       <div class="row margin">
        <div class="input-field col s12">
          <%= f.label :confirmed, "Statut de la bière" %><br><br>
          <%= f.select :confirmed, [['Valide', true], ['Invalide', false]], {}, prompt: 'Choisir de valider' , :class => 'browser-default'%>
        </div>
       </div>

        <div class="row">
           <div class="col s12 m5 l4"><p></p></div>
           <%= f.submit "Editer" , :class => "btn col s6 m3 l4 waves-light orange"%>
           <div class="col s12 m5 l4"><p></p></div>

         </div>
      </div>
    </form>
       <% end %>
    </div>
  </div>
  <% else %>
  <p>Vous n'avez pas les droits pour consulter cette page !</p>
  <% end %>

app/views/beers/index.html.erb
<% if signed_in? && current_user.admin? %>
<div class="container">
<h3><span class="span_h3 brown-text"><%=@title%></span></h3>
<div class="row">
  <table>
    <thead>
      <tr>
        <th data-field="state">Etat</th>
        <th data-field="name">Nom</th>
        <th data-field="degree">Degrés</th>
      </tr>
    </thead>

    <tbody>
      <% @beers.each do |beer| %>
        <tr>
          <% if beer.confirmed? %>
            <td><i class="material-icons">done</i></td>
          <% else %>
            <td><i class="material-icons">add</i></td>
          <% end %>
          <td><%= beer.name %></td>
          <td><%= beer.degree %></td>
          <td><%= link_to "Profil",  beer, :class => "brown-text text-brown" %> | <%= link_to "Editer", edit_beer_path(beer), :class => "brown-text text-brown" %></td>
          <td><%= button_to "Supprimer", beer, :method => :delete, :onclick => "return confirm('Etes-vous sûr de vouloir supprimer #{beer.name} ?')", :class => "orange lighten-2"%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
<p>Vous n'avez pas les droits pour consulter cette page !</p>
<% end %>

app/views/beers/new.html.erb
<div id="new_beer-page" class="container">
  <div class="col s12 ">
    <h3><span class="span_h3 brown-text"><%=@title%></span></h3>
    <%= form_for(@beer) do |f| %>
    <form class="login-form">
      <div class="row">
        <div class="input-field col s12 center">
        </div>
      </div>
       <div class="row margin">
        <div class="input-field col s12">
            <%= f.label :name, "Nom" %><br />
            <%= f.text_field :name %>
        </div>
      </div>
       <div class="row margin">
        <div class="input-field col s12">
          <%= f.label :degree, "Degré d'alcool" %>
          <%= f.number_field :degree , :step => 0.1, :value => 5 %><br />
        </div>
       </div>
       <div class="row margin">
        <div class="input-field col s12">
          <%= f.label :description, "Description" %>
          <%= f.text_area :description , :class => "materialize-textarea" %>
        </div>
       </div>
       <div class="row margin">
        <div class="input-field col s12">
          <%= f.label :story, "Histoire" %>
          <%= f.text_area :story , :class => "materialize-textarea" %>
        </div>
       </div>

       <div class="row margin">
        <div class="input-field col s12">
          <%= f.label :beer_category_id, "Catégorie" %><br><br>
          <%= f.select :beer_category_id,BeerCategory.all.collect { |cat| [cat.name, cat.id]}, {}, prompt: 'Choisir une catégorie' , :class => 'browser-default'%>
        </div>
       </div>

       <div class="row">
         <div class="input-field col s12">
           <%= f.label :picture, "Image représentant la bière" %><br><br>  
           <%= f.file_field :picture %>
         </div>
      </div>  

      <div class="row">
        <div class="col s12 m5 l4"><p></p></div>
           <%= f.submit "Ajouter" , :class => "btn col s6 m3 l4 waves-light orange"%>
        <div class="col s12 m5 l4"><p></p></div>
      </div>
    </form>
      <% end %>
  </div>
</div>

app/views/beers/show.html.erb
<div class="container">
  <div class="card-panel grey lighten-5 z-depth-1">
    <div class="row">
      <h3><span class="span_h3 brown-text"><%=@beer.name%></span></h3>
      <div class="col s12 m6 l0">
        <p>  <img src="../images/beer_profile/<%= @beer.id %>.jpg" alt="" class="responsive-img beer-profile z-depth-2 materialboxed"> <!-- notice the "circle" class --></p>
      </div>

      <div class="col s12 m6 l0">
        <ul>
          <li> <b>Degré :</b> <%= @beer.degree =%> </li>
          <li> <b>Catégorie :</b> <%= link_to @beer_category.name, @beer_category%></li>
          <li> <b>Note :</b> <%= @nbReviews.average(:note)%>/10  </li>
          <% if nbReviews(@nbReviews.count) %>
            <li>  <td><%= @nbReviews.count %></td> Collectionneurs l'ont déjà : <a href='/reviews/<%= @beer.id %>' >Consultez leurs avis ! </a> </li>
            <% elsif nbReviewsII(@nbReviews.count) %>
              <li>  <td><%= @nbReviews.count %></td> Collectionneur l'a déjà : <a href='/reviews/<%= @beer.id %>' >Consultez son avis ! </a> </li>
               <% else %>
                  <li>  Il n'y a pas encore d'avis concernant cette bière. </li>
          <% end %>
        </ul>
      <% if signed_in? %>
        <% if current_user.admin?%>
        <%= form_for @beer do |f| %>
          <%= f.hidden_field :id, :value => "#{@beer.id}"%>
          <%= f.file_field :picture %>
          <%= f.submit "Upload"%>
        <% end %>
        <% end %>
      <% end %>
     </div>
  </div>
  </div>
  <div class="col s12 m4 l4">
    <ul class = "collapsible active">
      <li >
      <div class="collapsible-header active"><i class="mdi-av-web a"></i>Description</div>
      <div class="collapsible-body active"><p><%= @beer.description %></p></div>
      </li>
    </ul>
  </div>
  <div class="col s12 m4 l4">
    <ul class = "collapsible active">
      <li >
        <div class="collapsible-header active"><i class="mdi-av-web a"></i>Histoire</div>
        <div class="collapsible-body active"><p><%= @beer.story %></p></div>
       </li>
    </ul>
  </div>
  <div class="col s12 m4 l4">
    <ul class = "collapsible active">
       <li >
        <div class="collapsible-header active"><i class="mdi-av-web a"></i>Avis de N.Voet l'expert</div>
        <div class="collapsible-body active"><p><%= @beer.description %></p></div>
      </li>
    </ul>
  </div>
</div>
<script src="../min/plugin-min.js"></script>
<script src="../min/custom-min.js"></script>