config/routes.rb
Rails.application.routes.draw do

resources :sessions, :only => [:new, :create, :destroy]
resources :users
resources :beers
resources :reviews
resources :beer_categories

resources :collections
resources :friends
resources :contacts, :only => [:new, :create]
resources :password_resets, :only => [:new, :create, :edit, :update]
resources :deals

  get 'sessions/new'
  get '/contact', :to => 'contacts#new'
  get '/admin_beers',   :to => 'pages#administration_beers'
  get '/admin_deals', :to => 'pages#administration_deals'
  get '/addbeer', :to => 'beers#new'
  get '/upload_img', :to => 'beers#upload_img'
  get '/handle_beers', :to => 'beers#index'
  get '/collections', :to => 'collections#show'
  get '/collections', :to => 'collections#destroy'
  get '/friends', :to => 'friends#show'
  get '/signup',  :to => 'users#new'

  get '/friendsRequest', :to => 'users#friendsRequest'
  get '/users',   :to => 'users#show'
  get '/handle_users', :to => 'users#index'
  post '/mlogin', :to => 'users#mlogin'

  get '/password_resets', :to => 'password_resets#new'

  get '/signin',  :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy', via: 'delete'
  get '/reviews', :to => 'reviews#show'
  root :to => 'pages#home'

  post '/api_login', :to => 'web_services#login'
  post '/api_register', :to => 'web_services#register'
  post '/api_beer_profile', :to => 'beers#show'
  get '/api_beer_profile', :to => 'beers#show'
  post '/api_add_beer', :to => 'collections#add_beer'
  post '/api_collection', :to => 'collections#show'
  post '/api_delete_beer', :to => 'collections#delete_beer'
  post '/api_user_profile', :to => 'users#api_show'
  get '/api_user_profile', :to => 'users#api_show'
  get '/api_bars', :to => 'bars#index'
  get '/api_shops', :to => 'shops#index'
  post '/api_comp', :to => 'web_services#img_comparator'
  get 'api_deals', :to => 'deals#index'
  post '/api_bars', :to => 'bars#index'
  post '/api_shops', :to => 'shops#index'
  post '/api_deals', :to => 'deals#index'

  get '/api_friends_map', :to => 'web_services#map_friends'
  post '/api_friends_map', :to => 'web_services#map_friends'
  get '/api_comp', :to => 'web_services#img_comparator'

  post '/api_add_catalogue', :to => 'web_services#add_to_catalogue'

  post '/api_friendlist', :to => 'friends#showFriendList'
  get '/api_friendlist', :to => 'friends#showFriendList'

  get '/api_beer_profile', :to => 'beers#show'

  post '/api_catalogue', :to => 'beer_categories#index'
  get '/catalogue', :to => 'beer_categories#index'
  post '/catalogue', :to => 'beer_categories#index'

  post '/addFriend', :to => 'friends#addFriend'
  get '/addFriend', :to => 'friends#addFriend'

  get '/users',   :to => 'users#show'
  post '/users',   :to => 'users#show'

  get '/beermap', :to => 'pages#beermap'

  get '/ajoutbonplan', :to =>'deals#new'
  post '/ajoutbonplan', :to=>'deals#new'

  get '/bonsplans', :to =>'deals#index'
  post '/bonsplans', :to =>'deals#index'

end

app/views/layouts/_footer.html.erb
<% if signed_in? && !current_user.admin? || !signed_in?%>
  <footer class="page-footer orange darken-3">
    <div class="footer-copyright ">
      <div class="container">

          <div class="row">

              <div class="col s12 m6 l0 footer-copyright colFooter">
                  © 2015 Copyright BeerCollection
                  <i class="mdi mdi-bell"></i>
              </div>

              <div class="col s12 m6 l0 colFooter">
                  <a href="<%= contact_path %>" class="waves-effect orange accent-2 lighten-1 waves-light btn"><i class="material-icons right">mail</i>Contact</a>
              </div>
             
              <div class="col s6 m2 l2"><p></p></div>
          </div>
        </div>
      </div>
    </div>
  </footer>
<% else %>
  <div class="fixed-action-btn horizontal click-to-toggle" style="bottom: 45px; right: 24px;">
    <a class="btn-floating btn-large orange">
      <i class="large mdi-navigation-menu"></i>
    </a>
    <ul>
      <li><a class="btn-floating orange" href="<%= handle_users_path %>"><i class="material-icons">supervisor_account</i></a></li>
      <li><a class="btn-floating orange" href="<%= admin_beers_path %>"><i class="material-icons">local_drink</i></a></li>
      <li><a class="btn-floating orange" href="<%= admin_deals_path %>"><i class="material-icons">attach_money</i></a></li>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<div class="navbar-fixed scrollspy">
    <nav id="nav_f" class="orange darken-3" role="navigation">
        <div class="container">
        <% if signed_in? %>

        <ul id="dropdown1" class="dropdown-content">
          <li><%= link_to "Profil", user_path(current_user), :class => "orange-text" %></li>
          <li><%= link_to "Collection", collection_path(current_user.id), :class => "orange-text" %></li>
          <li class="divider"></li>
          <li><%= link_to "Déconnexion", signout_path, :class => "orange-text" %></li>
        </ul>


  <div class="nav-wrapper">
            <a href="<%= root_path %>" id="logo-container" class="brand-logo">Beer Collection</a>
                <ul class="right hide-on-med-and-down">
                  <!-- <li><%= link_to "Profil", user_path(current_user) %></li>
                  <li><%= link_to "Ma collection", collection_path(current_user.id) %></li> -->
                  <li><%= link_to "Bons plans", bonsplans_path %></li>
                  <li><%= link_to "Catalogue", catalogue_path %></li>
                  <li><%= link_to "BeerMap", beermap_path %></li>
                  <!-- <li><%= link_to "Déconnexion", signout_path %></li> -->
                  <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= current_user.login %><i class="material-icons right">arrow_drop_down</i></a></li>
                </ul>
                <ul id="nav-mobile" class="side-nav">
                  <li><%= link_to "Profil", user_path(current_user) %></li>
                  <li><%= link_to "Ma collection", collection_path(current_user.id) %></li>
                  <li><%= link_to "Bons plans", bonsplans_path %></li>
                  <li><%= link_to "BeerMap", beermap_path %></li>
                  <li><%= link_to "Catalogue", catalogue_path %></li>
                  <li><%= link_to "Déconnexion", signout_path %></li>
                </ul>
            <a href="/" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
            </div>
      <% else %>
            <div class="nav-wrapper">
            <a href="<%= root_path %>" id="logo-container" class="brand-logo">Beer Collection</a>
                <ul class="right hide-on-med-and-down">
                  <li><%= link_to "Catalogue", catalogue_path %></li>
                  <li><%= link_to "BeerMap", beermap_path %></li>
                  <li><%= link_to "S'identifier", signin_path %></li>
                  <li><%= link_to "S'inscrire", signup_path %></li>
                </ul>
                <ul id="nav-mobile" class="side-nav">
                  <li><%= link_to "Catalogue", catalogue_path %></li>
                  <li><%= link_to "BeerMap", beermap_path %></li>
                  <li><%= link_to "S'identifier", signin_path %></li>
                  <li><%= link_to "S'inscrire", signup_path %></li>
                </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
            </div>
      <% end %>
        <div id="loader-wrapper">
    <div id="loader"></div>

    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
        <script src="../min/plugin-min.js"></script>
    <script src="../min/custom-min.js"></script>
</div>


        </div>
    </nav>
</div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script src="http://maps.googleapis.com/maps-api-v3/api/js/22/7/intl/fr_ALL/main.js"></script>
<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;extension=.js&amp;output=embed"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
<![endif]-->

<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

<%= stylesheet_link_tag 'materialize', :media => 'screen' %>
<%= stylesheet_link_tag 'materialize.min', :media => 'screen' %>
<%= stylesheet_link_tag 'style', :media => 'screen' %>


    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <meta name="theme-color" content="#2196F3"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <link href="css/materialdesignicons.min.css" media="all" rel="stylesheet" type="text/css" />
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <title>Beer Collection</title>
	<%= csrf_meta_tag %>

    <%= render 'layouts/stylesheets' %>

  </head>
  <body>
      <%= render 'layouts/header' %>

        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>

        <%= yield %>

      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.test? %>
  </div>
</body>
</html>